example:
	cd src && \
	javac -Xlint:unchecked -cp ".:../libs/json-simple-1.1.jar" alerts/example/*.java && \
	java -cp ".:../libs/json-simple-1.1.jar" alerts.example.Example

clean:
	rm src/alerts/example/*.class
	rm src/alerts/clients/*.class
